---
- name: CFME | Add Control Profile | Get the profile ID
  uri:
    url: https://localhost/api/policy_profiles?filter[]=name=VM+SmartState+Analysis+profile
    method: GET
    headers:
      X-Auth-Token: "{{ api_token }}"
    validate_certs: no
    body_format: json
  register: rest_return

- set_fact:
    control_profile_href: "{{ rest_return.json.resources[0].href }}"

- name: CFME | Add Control Profile | Assign the profile to the VMware provider IDs
  uri:
    url: https://localhost/api/providers/{{ item }}/policy_profiles
    method: POST
    headers:
      X-Auth-Token: "{{ api_token }}"
    validate_certs: no
    body_format: json
    body:
      action: assign
      resource:
        href: "{{ control_profile_href }}"
  with_items: "{{ vmware_provider_ids }}"
  register: rest_return
